# DBの設定
SQLALCHEMY_DATABASE_URI = "sqlite:///UC.db"
SQLALCHEMY_TRACK_MODIFICATIONS = True
# デバッグするか否か
DEBUG = True
# Secret key
SECRET_KEY = "3Mg18sO9K+g2rmX3LHQoIDQwHQ2DpXcCaUWPmFEC1FleeDK7k7hVkvvhdk6uIWmY4YtIzcHW9eNS5FPBNi6wM1BbDsOZpldwNPDuptoIWkwIbfKETCJSkUZsU3Eey79bcpASmbyORHMQjP/jhp8HKT4LkotHWn/7PXHjFmtn0FoowuamvsK15+myM3v80mfGLTm8yyddUNjKejksNiHwSdIfg6UEpluiSqIZDQmNG0430Nd7c6tjYqOWMMbviVB7oO+FhtJljwpQeRAaqRU8lnrpnnou44OtAkP1qC34h3bjxS++qHmbjjUyRAeO3p9aBfqt0dk9sCfnpp3KyKbWHA=="
# ファイル保存場所
UPLOAD_FOLDER = "files"
