SQLALCHEMY_DATABASE_URI = "sqlite:///flask_blog.db"
SQLALCHEMY_TRACK_MODIFICATIONS = True

DEBUG = True
USERNAME = "john"
PASSWORD = "due123"
SECRET_KEY = """3Mg18sO9K+g2rmX3LHQoIDQwHQ2DpXcCaUWPmFEC1FleeDK7k7hVkvvhdk6uIWmY4YtIzcHW9eNS
5FPBNi6wM1BbDsOZpldwNPDuptoIWkwIbfKETCJSkUZsU3Eey79bcpASmbyORHMQjP/jhp8HKT4L
kotHWn/7PXHjFmtn0FoowuamvsK15+myM3v80mfGLTm8yyddUNjKejksNiHwSdIfg6UEpluiSqIZ
DQmNG0430Nd7c6tjYqOWMMbviVB7oO+FhtJljwpQeRAaqRU8lnrpnnou44OtAkP1qC34h3bjxS++
qHmbjjUyRAeO3p9aBfqt0dk9sCfnpp3KyKbWHA=="""
